version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.0
    - 1.7.1
    - 1.8.0
  - dependency-name: github.com/google/go-cmp
    versions:
    - 0.5.4
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.1
    - 1.1.2
