---
kind: pipeline
type: docker
name: tests

global-variables:
  environment: &default_environment
    GOPATH:     "/go"
    GOCACHE:    "/go/.cache/go-build"
    GOENV:      "/go/.config/go/env"
    GOMODCACHE: "/go/pkg/mod"
steps:
  - name: pull
    image: omerxx/drone-ecr-auth
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
      - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.0.5
      - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:2022-02-11
      - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:cran-latest
    volumes:
      - name: docker.sock
        path: /var/run/docker.sock
  - name: build
    image: golang:1.16
    environment:
      <<: *default_environment
    commands:
      - make install
      - go get ./...
    volumes:
      - name: go
        path: /go
  - name: configlib, no system renv
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - cd configlib
      - go test -v .
  - name: configlib, system renv (< 0.15)
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:2022-02-11
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PKGR_TESTS_SYS_RENV=1
      - cd configlib
      - go test -v .
  - name: configlib, system renv (>= 0.15)
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:cran-latest
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PKGR_TESTS_SYS_RENV=1
      - cd configlib
      - go test -v .
  - name: gpsr
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - cd gpsr
      - go test -v .
  - name: cran
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - cd cran
      - go test -v .
  - name: baseline
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/baseline
      - make test
  - name: version
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/version
      - make test
  - name: rollback
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/rollback
      - make test
  - name: outdated
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/outdated-pkgs
      - make test
  - name: load
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/load
      - make test
  - name: multi-repo
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/multi-repo
      - make test
  - name: bad-customization
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/bad-customization
      - make test
  - name: recommended-packages
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/recommended
      - make test
  - name: rpath-env-var
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/env-vars
      - make test
  - name: tarball-install
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/tarball-install
      - make test
  - name: libraries
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.1.0
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/library
      - make test
  - name: libraries, system renv (< 0.15)
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:2022-02-11
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - export PKGR_TESTS_SYS_RENV=1
      - cd integration_tests/library
      - make test
  - name: libraries, system renv (>= 0.15)
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:cran-latest
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - export PKGR_TESTS_SYS_RENV=1
      - cd integration_tests/library
      - make test
  - name: mixed-source-and-customizations
    image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci:4.0.5
    pull: never
    volumes:
      - name: go
        path: /go
    environment:
      <<: *default_environment
    commands:
      - export PATH=/go/bin:$PATH
      - cd integration_tests/mixed-source
      - make test
volumes:
  - name: docker.sock
    host:
      path: /var/run/docker.sock
  - name: go
    temp: { }

---
kind: pipeline
type: docker
name: goreleaser

platform:
  os: linux
  arch: amd64

steps:
  - name: goreleaser
    image: goreleaser/goreleaser
    commands:
      - git config --global user.email "drone@metrumrg.com"
      - git config --global user.name "Drony"
      - git fetch --tags
      - cd cmd/pkgr
      - goreleaser --rm-dist
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      VERSION: ${DRONE_TAG}

trigger:
  event:
    - tag

depends_on:
  - tests
