package gpsr

// DefaultPackages shows the default packages and where they come from
var DefaultPackages = map[string]string{
	"base":       "base",
	"compiler":   "base",
	"datasets":   "base",
	"graphics":   "base",
	"grDevices":  "base",
	"grid":       "base",
	"methods":    "base",
	"parallel":   "base",
	"splines":    "base",
	"stats":      "base",
	"stats4":     "base",
	"tcltk":      "base",
	"tools":      "base",
	"utils":      "base",
	"Matrix":     "recommended",
	"boot":       "recommended",
	"class":      "recommended",
	"cluster":    "recommended",
	"codetools":  "recommended",
	"foreign":    "recommended",
	"KernSmooth": "recommended",
	"lattice":    "recommended",
	"MASS":       "recommended",
	"mgcv":       "recommended",
	"nlme":       "recommended",
	"nnet":       "recommended",
	"rpart":      "recommended",
	"spatial":    "recommended",
	"survival":   "recommended",
}
