#!/bin/sh

set -eu

ls_pkgs () {
    go list ./... |
        grep -vE '/internal/valtools/[a-z]+$' |
        grep -vE '/internal/tools/docgen$' |
        grep -vF '/integration_tests/' |
        tr '\n' ' '
}

pkgs=$(ls_pkgs)
pkgs=${pkgs% *}
cpkgs=$(printf '%s' "$pkgs" | tr ' ' ',')

tdir=$(mktemp -d "${TMPDIR:-/tmp}"/pkgr-test-XXXXX)
trap 'rm -rf "$tdir"' 0
# Prevent tests from touching user's real cache.
export XDG_CACHE_HOME="$tdir"

run () {
    go test -p 1 -count 1 "$@"
}

# Unset R_LIBS_{USER,SITE} to prevent the warning from
# rcmd.configureEnv tripping up TestLoad's check for expected output.
unset R_LIBS_USER
unset R_LIBS_SITE
export PKGR_TESTS_SYS_RENV="${PKGR_TESTS_SYS_RENV-1}"
if test -n "${GOCOVERDIR-}"
then
    printf >&2 'testing with -cover\n'
    # shellcheck disable=SC2086
    run -cover -coverpkg="$cpkgs" "$@" $pkgs \
        -args -test.gocoverdir="$GOCOVERDIR"
else
    # shellcheck disable=SC2086
    run "$@" $pkgs
fi
